spring.application.name=sendMail

# Server port (optional)
server.port=2020

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Security?useSSL=false
spring.datasource.username=root
spring.datasource.password=Ritik@900
spring.jackson.stream-write-constraints.max-nesting-depth=1000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Driver (usually auto-detected, but safe to add)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


cipher.algo = AES
encryption.algorithm =AES/GCM/NoPadding

jwt.secret=sdjbshbfhdbfhbfdfijfioffuurhurrgh

